spring:
  datasource:
    url: jdbc:mysql://localhost:3306/isdn_db?useSSL=false&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true
    username: isdn_user
    password: isdn_password_123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.isdn: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080